title: partsbin
email: me@becdetat.com
description: >-
  The ultimate tool for hobbyist hardware hackers and engineers, giving you a
  simple application with smart search capabilities, designed to streamline
  managing your parts inventory
baseurl: ""
url: "https://partsbin.page"
github_username:  becdetat
theme: minima
plugins:
  - jekyll-feed
